// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "f607a085-c082-4719-906f-8013122e6165";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onBarrierZebraChange();
void onSmartSignalChange();

bool barrier_zebra;
bool smart_signal;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(barrier_zebra, READWRITE, ON_CHANGE, onBarrierZebraChange);
  ArduinoCloud.addProperty(smart_signal, READWRITE, ON_CHANGE, onSmartSignalChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
